scene: rgbd_dataset_freiburg1_desk2
inherit_from: configs/TUM_RGBD/tum.yaml
config_path: configs/TUM_RGBD/freiburg1_desk2.yaml
data:
  input_folder: /home/esandstroem/scratch-second/opportunistic_3d_capture/data/tum/rgbd_dataset_freiburg1_desk2
  output: output/TUM_RGBD/rgbd_dataset_freiburg1_desk2
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 8
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]